import { User } from '@/types';

export const users: User[] = [
    // ========================
    // FOCAL PERSONS (5)
    // ========================
    {
        id: 1,
        employee_code: 'EMP-001',
        name: 'Maria Santos',
        first_name: 'Maria',
        middle_name: undefined,
        last_name: 'Santos',
        gender: 'Female',
        department: 'DILG',
        position: 'Program Focal Person',
        birthday: new Date('1990-03-12'),
        email: 'maria.santos@example.com',
        avatar: undefined,
        email_verified_at: '2026-01-01T08:00:00Z',
        two_factor_enabled: false,
        created_at: '2026-01-01T08:00:00Z',
        updated_at: '2026-01-01T08:00:00Z',
        role: 'focal_person',
    },
    {
        id: 2,
        employee_code: 'EMP-002',
        name: 'John Mercado',
        first_name: 'John',
        middle_name: undefined,
        last_name: 'Mercado',
        gender: 'Male',
        department: 'DILG',
        position: 'Program Focal Person',
        birthday: new Date('1988-07-21'),
        email: 'john.mercado@example.com',
        avatar: undefined,
        email_verified_at: '2026-01-02T09:15:00Z',
        two_factor_enabled: false,
        created_at: '2026-01-02T09:15:00Z',
        updated_at: '2026-01-02T09:15:00Z',
        role: 'focal_person',
    },
    {
        id: 3,
        employee_code: 'EMP-003',
        name: 'Ariana Dela Cruz',
        first_name: 'Ariana',
        middle_name: undefined,
        last_name: 'Dela Cruz',
        gender: 'Female',
        department: 'DILG',
        position: 'Program Focal Person',
        birthday: new Date('1993-11-05'),
        email: 'ariana.delacruz@example.com',
        avatar: undefined,
        email_verified_at: null,
        two_factor_enabled: false,
        created_at: '2026-01-03T10:20:00Z',
        updated_at: '2026-01-03T10:20:00Z',
        role: 'focal_person',
    },
    {
        id: 4,
        employee_code: 'EMP-004',
        name: 'Edward Ramirez',
        first_name: 'Edward',
        middle_name: undefined,
        last_name: 'Ramirez',
        gender: 'Male',
        department: 'DILG',
        position: 'Program Focal Person',
        birthday: new Date('1987-01-18'),
        email: 'edward.ramirez@example.com',
        avatar: undefined,
        email_verified_at: '2026-01-04T11:45:00Z',
        two_factor_enabled: false,
        created_at: '2026-01-04T11:45:00Z',
        updated_at: '2026-01-04T11:45:00Z',
        role: 'focal_person',
    },
    {
        id: 5,
        employee_code: 'EMP-005',
        name: 'Camille Soriano',
        first_name: 'Camille',
        middle_name: undefined,
        last_name: 'Soriano',
        gender: 'Female',
        department: 'DILG',
        position: 'Program Focal Person',
        birthday: new Date('1991-06-30'),
        email: 'camille.soriano@example.com',
        avatar: undefined,
        email_verified_at: null,
        two_factor_enabled: false,
        created_at: '2026-01-05T12:30:00Z',
        updated_at: '2026-01-05T12:30:00Z',
        role: 'focal_person',
    },

    // ========================
    // FIELD OFFICERS (5)
    // ========================
    {
        id: 6,
        employee_code: 'EMP-006',
        name: 'Joseph Manalo',
        first_name: 'Joseph',
        middle_name: undefined,
        last_name: 'Manalo',
        gender: 'Male',
        department: 'DILG',
        position: 'Field Officer',
        birthday: new Date('1992-11-04'),
        email: 'joseph.manalo@example.com',
        avatar: undefined,
        email_verified_at: null,
        two_factor_enabled: false,
        created_at: '2026-01-06T07:10:00Z',
        updated_at: '2026-01-06T07:10:00Z',
        role: 'field_officer',
    },
    {
        id: 7,
        employee_code: 'EMP-007',
        name: 'Grace Bautista',
        first_name: 'Grace',
        middle_name: undefined,
        last_name: 'Bautista',
        gender: 'Female',
        department: 'DILG',
        position: 'Field Officer',
        birthday: new Date('1994-09-14'),
        email: 'grace.bautista@example.com',
        avatar: undefined,
        email_verified_at: '2026-01-06T13:00:00Z',
        two_factor_enabled: false,
        created_at: '2026-01-06T13:00:00Z',
        updated_at: '2026-01-06T13:00:00Z',
        role: 'field_officer',
    },
    {
        id: 8,
        employee_code: 'EMP-008',
        name: 'Leo Fernandez',
        first_name: 'Leo',
        middle_name: undefined,
        last_name: 'Fernandez',
        gender: 'Male',
        department: 'DILG',
        position: 'Field Officer',
        birthday: new Date('1989-05-27'),
        email: 'leo.fernandez@example.com',
        avatar: undefined,
        email_verified_at: null,
        two_factor_enabled: false,
        created_at: '2026-01-07T09:45:00Z',
        updated_at: '2026-01-07T09:45:00Z',
        role: 'field_officer',
    },
    {
        id: 9,
        employee_code: 'EMP-009',
        name: 'Sophia Cruz',
        first_name: 'Sophia',
        middle_name: undefined,
        last_name: 'Cruz',
        gender: 'Female',
        department: 'DILG',
        position: 'Field Officer',
        birthday: new Date('1995-02-10'),
        email: 'sophia.cruz@example.com',
        avatar: undefined,
        email_verified_at: null,
        two_factor_enabled: false,
        created_at: '2026-01-08T16:20:00Z',
        updated_at: '2026-01-08T16:20:00Z',
        role: 'field_officer',
    },
    {
        id: 10,
        employee_code: 'EMP-010',
        name: 'Nathan Villanueva',
        first_name: 'Nathan',
        middle_name: undefined,
        last_name: 'Villanueva',
        gender: 'Male',
        department: 'DILG',
        position: 'Field Officer',
        birthday: new Date('1990-12-01'),
        email: 'nathan.villanueva@example.com',
        avatar: undefined,
        email_verified_at: '2026-01-08T17:00:00Z',
        two_factor_enabled: false,
        created_at: '2026-01-08T17:00:00Z',
        updated_at: '2026-01-08T17:00:00Z',
        role: 'field_officer',
    },
];
